### ISSUE TITLE
STest::Pick::lowerUpper() picks a value outside the specified lower/upper values

### ISSUE THREAD

**Issue by sfregoso** [fprime-community/stest#1]
I have an issue where the STest::Pick::lowerUpper() function picks a value that is outside the lower and upper values.

In the code snippet below, NO_ERROR is value 0, and CMD_PIPE_FAILED is 2003, yet it returned a value of 2004.

The seed that causes this is 342457

We are using FPRIME 3.0.

![image](https://github.com/fprime-community/stest/assets/51178479/af710916-c45e-4706-9af5-752f17d2d388)

**Comment by bocchino** [comment]
Good catch, I'll try to implement a fix soon.

**Comment by bocchino** [comment]
Fixed in commit de5ed3d36bc3fdc21134b4c3652fe7f28b0f2cfc.
